### ISSUE TITLE
HDDL parser doesn't support ordering subtasks together when those subtasks are actions

### ISSUE THREAD

**Issue by nandangrover** [Maumagnaguagno/HyperTensioN#7] opened 2022-01-29 21:13 UTC
If the subtasks are chained together in a method, then the parser doesn't save the state of those actions that were chained. For ex:

```
(:method test_method
        :parameters (?from ?to ?destination - object)
        :task
        (goto ?test ?destination)
        :precondition (and (loc ?test ?from) (adj ?from ?to))
        :ordered-subtasks
        (and (action_1 ?hero ?from ?to) (action_2 ?hero ?from ?to) (goto ?hero ?destination))
  )
```

The state changes in action_1 are not reflected for action_2.

**Comment by Maumagnaguagno** [comment] 2022-01-30 07:44
Not sure which state you are referring to, parsers only read the input files to fill the internal structures, while the state change later during planning-time.

If your method is ever decomposed and its preconditions satisfied by the current state, the subtasks with **free variables ground at this point** replace the current task and the decomposition process continues.
If a subtask fails the planner backtracks and tries other unifications and methods to solve that task, undoing previous state changes.
This is easy to see in the [Basic HDDL example](../blob/master/examples/basic/basic.hddl) where someone wants to trade a banjo for a kiwi or vice versa.
The ``swap`` task tries the ``have_first`` method, it fails, and without free variables to be unified differently it tries ``have_second``.
If a sequence of subtasks (which you called chain) was not possible this instance would have zero or two ``have`` predicates at the final state, but it is working as expected so the problem is elsewhere.

The variable ``?hero`` remains free in your example, it should either be propagated through ``:task`` variables or unified by ``:preconditions``.
This is probably the reason it fails, you can check for common mistakes with the Wise extension: ``ruby Hype.rb <domain> <problem> wise run``.
It should display something like this: ``method goto test_method never declared variable ?hero from (action_1 ?hero ?from ?to)``.

**Comment by Maumagnaguagno** [comment] 2022-02-06 06:47
Considering there was no feedback I will close this issue in a few days if nothing happens.

**Closed as completed** 2022-02-09 17:27 UTC
